AR = ['C:/n64-toolchain\\bin\\mips64-elf-gcc-ar.exe']
ARFLAGS = ['rcs']
AS = ['C:/n64-toolchain\\bin\\mips64-elf-gcc.exe']
ASFLAGS = ['-march=vr4300', '-mtune=vr4300', '-Os', '-DNDEBUG', '-G0', '-fno-PIC', '-mno-abicalls', '-DN64', '-ffunction-sections', '-fdata-sections', '-ffast-math', '-fno-ident', '-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-flto', '-fcommon', '-IC:/n64-toolchain\\mips64-elf\\include', '-IC:/n64-toolchain\\include']
ASLNK_TGT_F = ['-o']
ASMPATH_ST = '-I%s'
ASM_NAME = 'gas'
AS_TGT_F = ['-c', '-o']
BINDIR = '${PREFIX}/lib/xash3d'
CC = ['C:/n64-toolchain\\bin\\mips64-elf-gcc.exe']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('14', '2', '0')
CFLAGS = ['-march=vr4300', '-mtune=vr4300', '-Os', '-DNDEBUG', '-G0', '-fno-PIC', '-mno-abicalls', '-DN64', '-ffunction-sections', '-fdata-sections', '-ffast-math', '-fno-ident', '-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-flto', '-fcommon', '-IC:/n64-toolchain\\mips64-elf\\include', '-IC:/n64-toolchain\\include']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
COMPILER_CXX = 'g++'
CPPPATH_ST = '-I%s'
CXX = ['C:/n64-toolchain\\bin\\mips64-elf-g++.exe']
CXXFLAGS = ['-march=vr4300', '-mtune=vr4300', '-Os', '-DNDEBUG', '-G0', '-fno-PIC', '-mno-abicalls', '-DN64', '-ffunction-sections', '-fdata-sections', '-ffast-math', '-fno-ident', '-fno-exceptions', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-flto', '-fcommon', '-IC:/n64-toolchain\\mips64-elf\\include', '-IC:/n64-toolchain\\include']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = ['-fPIC']
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DEFINES = ['XASH_BUILD_COMMIT="notset"', 'XASH_LOW_MEMORY=2', 'XASH_EXT_OPT=2', 'SINGLE_BINARY=1', 'STDINT_H="stdint.h"', 'HAVE_TGMATH_H=1']
DEFINES_ST = '-D%s'
DEFINE_COMMENTS = {'XASH_BUILD_COMMIT': '', 'XASH_LOW_MEMORY': '', 'XASH_EXT_OPT': '', 'SINGLE_BINARY': '', 'STDINT_H': '', 'HAVE_TGMATH_H': '', 'XASH_NO_NETWORK': '', 'XASH_NO_LIBDL': '', 'XASH_STATIC_LIBS': '', 'XASH_CUSTOM_SWAP': '', 'XASH_NO_ASYNC_NS_RESOLVE': '', 'XASH_USE_SELECT': '', 'SUPPORT_BSP2_FORMAT': '', 'XASH_64BIT': '', 'DBGHELP': '', 'PSAPI_VERSION': ''}
DEST_BINFMT = 'elf'
DEST_CPU = 'mips'
DEST_OS = 'n64'
DEST_OS2 = 'n64'
IGNORE_PROJECTS = ['ref_gl', 'stub/server', 'stub/client', 'mainui']
LD = ['C:/n64-toolchain\\bin\\mips64-elf-gcc.exe']
LDFLAGS = ['-TC:\\libdragon-dev\\examples\\hlport\\xash3d-fwgs\\n64.ld', '-LC:/n64-toolchain\\mips64-elf\\lib', '-LC:/n64-toolchain\\lib', '-Wl,--gc-sections', '-Wl,--wrap,__do_global_ctors', '-Wl,-s', '-flto', '-Wl,-z,muldefs', '-Wl,--start-group', '-ldragon', '-ldragonsys', '-lc', '-lm', '-Wl,--end-group']
LIBDIR = '${PREFIX}/lib/xash3d'
LIBPATH_ST = '-L%s'
LIB_M = ['m']
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CC = ['C:/n64-toolchain\\bin\\mips64-elf-gcc.exe']
LINK_CXX = ['C:/n64-toolchain\\bin\\mips64-elf-g++.exe']
N64ELFCOMPRESS = ['C:/n64-toolchain\\bin\\n64elfcompress.exe']
N64SYM = ['C:/n64-toolchain\\bin\\n64sym.exe']
N64TOOL = ['C:/n64-toolchain\\bin\\n64tool.exe']
N64MKDFS = ['C:/n64-toolchain\\bin\\mkdfs.exe']
OBJCOPY = ['C:/n64-toolchain\\bin\\mips64-elf-objcopy.exe']
PREFIX = 'C:\\Users\\dylan\\AppData\\Local\\Temp'
RANLIB = ['C:/n64-toolchain\\bin\\mips64-elf-gcc-ranlib.exe']
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SINGLE_BINARY = True
SONAME_ST = '-Wl,-h,%s'
STATIC_LINKING = 'ref_soft'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
STRIP = ['C:/n64-toolchain\\bin\\mips64-elf-strip.exe']
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
cxxprogram_PATTERN = '%s'
cxxshlib_PATTERN = 'lib%s.so'
cxxstlib_PATTERN = 'lib%s.a'
define_key = ['XASH_BUILD_COMMIT', 'XASH_LOW_MEMORY', 'XASH_EXT_OPT', 'SINGLE_BINARY', 'STDINT_H', 'HAVE_TGMATH_H']
macbundle_PATTERN = '%s.bundle'
